# Generated by Django 2.2.3 on 2019-10-20 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20191020_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='datePosted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
