# Generated by Django 2.2.3 on 2019-10-20 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20191020_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
