# Generated by Django 2.2.3 on 2019-10-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_movement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=20),
        ),
    ]
