# Generated by Django 2.2.3 on 2019-10-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_movement_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='type',
            field=models.CharField(default='In', max_length=10),
        ),
    ]
