# Generated by Django 2.2.3 on 2019-11-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20191021_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
